version: '3.8'
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"

volumes:
  postgres_data: